# Generated by Django 2.2.5 on 2019-09-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.SlugField(max_length=32)),
            ],
            options={
                'db_table': 'accounts_api_token',
                'managed': False,
            },
        ),
    ]
