# Generated by Django 2.2.5 on 2019-09-16 00:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialPrimerPairs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('persist_file', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('version', models.CharField(max_length=16)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mopo16s_initial_primer_pairs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField()),
                ('is_uploaded', models.BooleanField()),
                ('mopo16s_version', models.CharField(default='1.0', max_length=16)),
                ('mopo16s_parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mopo16s_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepresentativeSequenceSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('persist_file', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('is_curated', models.BooleanField()),
                ('version', models.CharField(max_length=16)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mopo16s_representative_sequence_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('error_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'mopo16s_run',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='result', related_query_name='result', serialize=False, to='mopo16s_web.Run')),
                ('init_primers', models.TextField()),
                ('init_scores', models.TextField()),
                ('out_primers', models.TextField()),
                ('out_scores', models.TextField()),
            ],
            options={
                'db_table': 'mopo16s_result',
                'managed': False,
            },
        ),
    ]
