# Generated by Django 2.2.5 on 2019-09-16 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('apitoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.ApiToken')),
            ],
            bases=('accounts.apitoken',),
        ),
    ]
