# Generated by Django 2.2.5 on 2019-09-16 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apitoken'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.apitoken',),
        ),
    ]
